const fs = require('fs');
const path = require('path');

const ALL_40_TASKS = [
  { taskId: 'T001', taskName: 'Activate company account', applicableRole: 'All', department: 'All', day: 'Day 1', priority: 'High', assignedBy: 'IT', resourceId: 'R002', isMandatory: true, duration: '20 mins', desc: 'Activate corporate single sign-on credentials and verify user directory profile.' },
  { taskId: 'T002', taskName: 'Set up MFA', applicableRole: 'All', department: 'All', day: 'Day 1', priority: 'High', assignedBy: 'IT', resourceId: 'R003', isMandatory: true, duration: '15 mins', desc: 'Configure corporate multi-factor authenticator and register security passkey.' },
  { taskId: 'T003', taskName: 'Complete employee profile', applicableRole: 'All', department: 'All', day: 'Day 1', priority: 'Medium', assignedBy: 'HR', resourceId: 'R001', isMandatory: true, duration: '20 mins', desc: 'Submit emergency contacts, statutory identity docs, and personal bio.' },
  { taskId: 'T004', taskName: 'Read employee handbook', applicableRole: 'All', department: 'All', day: 'Day 1', priority: 'Medium', assignedBy: 'HR', resourceId: 'R001', isMandatory: true, duration: '30 mins', desc: 'Review corporate mission, workplace conduct rules, and company values.' },
  { taskId: 'T005', taskName: 'Complete security awareness training', applicableRole: 'All', department: 'All', day: 'Day 1', priority: 'High', assignedBy: 'Security', resourceId: 'R004', isMandatory: true, duration: '25 mins', desc: 'Complete mandatory cyber threat, phishing defense, and data protection module.' },
  { taskId: 'T006', taskName: 'Meet onboarding buddy', applicableRole: 'All', department: 'All', day: 'Day 1', priority: 'Medium', assignedBy: 'Manager', resourceId: null, isMandatory: true, duration: '40 mins', desc: 'Connect 1-on-1 with your assigned senior buddy for workplace norms and team intro.' },
  { taskId: 'T007', taskName: 'Attend company orientation', applicableRole: 'All', department: 'All', day: 'Day 1', priority: 'High', assignedBy: 'HR', resourceId: 'R005', isMandatory: true, duration: '45 mins', desc: 'Join welcome orientation session with People Operations and leadership team.' },
  { taskId: 'T008', taskName: 'Set up company email', applicableRole: 'All', department: 'All', day: 'Day 1', priority: 'High', assignedBy: 'IT', resourceId: 'R002', isMandatory: true, duration: '15 mins', desc: 'Configure corporate mailbox, calendar sync, and email signature.' },
  { taskId: 'T009', taskName: 'Review leave and attendance policy', applicableRole: 'All', department: 'All', day: 'Day 2', priority: 'Medium', assignedBy: 'HR', resourceId: 'R006', isMandatory: true, duration: '20 mins', desc: 'Learn leave application process, holiday calendars, and working hour policies.' },
  { taskId: 'T010', taskName: 'Review company benefits', applicableRole: 'All', department: 'All', day: 'Day 2', priority: 'Low', assignedBy: 'HR', resourceId: 'R007', isMandatory: false, duration: '25 mins', desc: 'Explore health insurance, wellness stipends, and retirement benefits.' },
  { taskId: 'T011', taskName: 'Complete workplace safety training', applicableRole: 'All', department: 'All', day: 'Day 2', priority: 'Medium', assignedBy: 'HR', resourceId: 'R008', isMandatory: true, duration: '20 mins', desc: 'Complete workplace ergonomics, fire safety, and emergency protocol module.' },
  { taskId: 'T012', taskName: 'Meet reporting manager', applicableRole: 'All', department: 'All', day: 'Day 2', priority: 'High', assignedBy: 'Manager', resourceId: null, isMandatory: true, duration: '45 mins', desc: 'Align on first-week priorities, 30-60-90 day milestones, and expectations.' },
  { taskId: 'T013', taskName: 'Join department communication channel', applicableRole: 'All', department: 'All', day: 'Day 2', priority: 'Medium', assignedBy: 'Manager', resourceId: null, isMandatory: true, duration: '15 mins', desc: 'Join squad Slack/Teams channels and bookmark team knowledge bases.' },
  // Software Engineer
  { taskId: 'T014', taskName: 'Set up GitHub access', applicableRole: 'Software Engineer', department: 'Engineering', day: 'Day 1', priority: 'High', assignedBy: 'IT', resourceId: 'R009', isMandatory: true, duration: '20 mins', desc: 'Accept enterprise GitHub organization invitation and link SSH signing keys.' },
  { taskId: 'T015', taskName: 'Set up development environment', applicableRole: 'Software Engineer', department: 'Engineering', day: 'Day 1', priority: 'High', assignedBy: 'Manager', resourceId: 'R010', isMandatory: true, duration: '60 mins', desc: 'Install IDE, compilers, container runtime, and run local test suite.' },
  { taskId: 'T016', taskName: 'Read engineering coding guidelines', applicableRole: 'Software Engineer', department: 'Engineering', day: 'Day 2', priority: 'Medium', assignedBy: 'Manager', resourceId: 'R011', isMandatory: true, duration: '30 mins', desc: 'Read code formatting, linting rules, PR review SLAs, and branch naming conventions.' },
  { taskId: 'T017', taskName: 'Review software architecture', applicableRole: 'Software Engineer', department: 'Engineering', day: 'Day 2', priority: 'Medium', assignedBy: 'Manager', resourceId: 'R012', isMandatory: true, duration: '45 mins', desc: 'Review microservice blueprints, database schemas, and API gateway specs.' },
  { taskId: 'T018', taskName: 'Join engineering repository', applicableRole: 'Software Engineer', department: 'Engineering', day: 'Day 2', priority: 'High', assignedBy: 'IT', resourceId: 'R013', isMandatory: true, duration: '20 mins', desc: 'Clone monorepo, configure pre-commit hooks, and verify local build.' },
  { taskId: 'T019', taskName: 'Complete code security training', applicableRole: 'Software Engineer', department: 'Engineering', day: 'Day 3', priority: 'High', assignedBy: 'Security', resourceId: 'R014', isMandatory: true, duration: '35 mins', desc: 'Learn SAST/DAST scanning, secret management, and secure dependency handling.' },
  { taskId: 'T020', taskName: 'Meet engineering team', applicableRole: 'Software Engineer', department: 'Engineering', day: 'Day 3', priority: 'Medium', assignedBy: 'Manager', resourceId: null, isMandatory: true, duration: '45 mins', desc: 'Join sprint planning or team standup to introduce yourself to teammates.' },
  // Data Analyst
  { taskId: 'T021', taskName: 'Set up analytics tools', applicableRole: 'Data Analyst', department: 'Data', day: 'Day 1', priority: 'High', assignedBy: 'Manager', resourceId: 'R015', isMandatory: true, duration: '30 mins', desc: 'Configure Power BI, Tableau, dbt CLI, and Python analytical libraries.' },
  { taskId: 'T022', taskName: 'Get access to data warehouse', applicableRole: 'Data Analyst', department: 'Data', day: 'Day 1', priority: 'High', assignedBy: 'IT', resourceId: 'R016', isMandatory: true, duration: '25 mins', desc: 'Request read permissions for Snowflake/BigQuery staging schemas.' },
  { taskId: 'T023', taskName: 'Review data governance policy', applicableRole: 'Data Analyst', department: 'Data', day: 'Day 2', priority: 'High', assignedBy: 'Data Lead', resourceId: 'R017', isMandatory: true, duration: '30 mins', desc: 'Understand PII data masking, compliance guidelines, and export policies.' },
  { taskId: 'T024', taskName: 'Review reporting standards', applicableRole: 'Data Analyst', department: 'Data', day: 'Day 2', priority: 'Medium', assignedBy: 'Data Lead', resourceId: 'R018', isMandatory: true, duration: '25 mins', desc: 'Study standard corporate metric definitions, KPI models, and dashboard templates.' },
  { taskId: 'T025', taskName: 'Meet data team', applicableRole: 'Data Analyst', department: 'Data', day: 'Day 3', priority: 'Medium', assignedBy: 'Manager', resourceId: null, isMandatory: true, duration: '40 mins', desc: 'Meet data engineers and business intelligence peers to discuss current pipelines.' },
  // UI/UX Designer
  { taskId: 'T026', taskName: 'Set up design tools', applicableRole: 'UI/UX Designer', department: 'Design', day: 'Day 1', priority: 'High', assignedBy: 'IT', resourceId: 'R019', isMandatory: true, duration: '25 mins', desc: 'Activate Figma enterprise seat, font packages, and asset libraries.' },
  { taskId: 'T027', taskName: 'Get access to design repository', applicableRole: 'UI/UX Designer', department: 'Design', day: 'Day 1', priority: 'High', assignedBy: 'IT', resourceId: 'R020', isMandatory: true, duration: '20 mins', desc: 'Request access to Figma workspace, component tokens, and UX research archives.' },
  { taskId: 'T028', taskName: 'Review design system', applicableRole: 'UI/UX Designer', department: 'Design', day: 'Day 2', priority: 'Medium', assignedBy: 'Design Lead', resourceId: 'R021', isMandatory: true, duration: '40 mins', desc: 'Study typography tokens, elevation scales, grid systems, and component states.' },
  { taskId: 'T029', taskName: 'Review brand guidelines', applicableRole: 'UI/UX Designer', department: 'Design', day: 'Day 2', priority: 'Medium', assignedBy: 'Design Lead', resourceId: 'R022', isMandatory: true, duration: '30 mins', desc: 'Review brand voice, color harmony, iconography, and illustration guidelines.' },
  { taskId: 'T030', taskName: 'Meet design team', applicableRole: 'UI/UX Designer', department: 'Design', day: 'Day 3', priority: 'Medium', assignedBy: 'Manager', resourceId: null, isMandatory: true, duration: '45 mins', desc: 'Attend weekly design critique and introduce yourself to product designers.' },
  // HR Executive
  { taskId: 'T031', taskName: 'Get access to HR portal', applicableRole: 'HR Executive', department: 'Human Resources', day: 'Day 1', priority: 'High', assignedBy: 'IT', resourceId: 'R023', isMandatory: true, duration: '25 mins', desc: 'Acquire administrative access to HRIS, Workday, and applicant tracker.' },
  { taskId: 'T032', taskName: 'Review HR policies', applicableRole: 'HR Executive', department: 'Human Resources', day: 'Day 1', priority: 'High', assignedBy: 'HR Manager', resourceId: 'R024', isMandatory: true, duration: '40 mins', desc: 'Study grievance procedures, leave policies, compensation bands, and onboarding flows.' },
  { taskId: 'T033', taskName: 'Review employee records process', applicableRole: 'HR Executive', department: 'Human Resources', day: 'Day 2', priority: 'High', assignedBy: 'HR Manager', resourceId: 'R025', isMandatory: true, duration: '30 mins', desc: 'Understand document verification, compliance filing, and digital dossier retention.' },
  { taskId: 'T034', taskName: 'Complete HR compliance training', applicableRole: 'HR Executive', department: 'Human Resources', day: 'Day 2', priority: 'High', assignedBy: 'HR Manager', resourceId: 'R026', isMandatory: true, duration: '35 mins', desc: 'Complete statutory labor law, workplace equality, and POSH training certification.' },
  { taskId: 'T035', taskName: 'Meet HR team', applicableRole: 'HR Executive', department: 'Human Resources', day: 'Day 3', priority: 'Medium', assignedBy: 'HR Manager', resourceId: null, isMandatory: true, duration: '45 mins', desc: 'Join the People Operations weekly sync and meet recruitment & talent partners.' },
  // Marketing Executive
  { taskId: 'T036', taskName: 'Set up marketing tools', applicableRole: 'Marketing Executive', department: 'Marketing', day: 'Day 1', priority: 'High', assignedBy: 'IT', resourceId: 'R027', isMandatory: true, duration: '30 mins', desc: 'Get access to HubSpot, Google Analytics 4, SEMrush, and social management tools.' },
  { taskId: 'T037', taskName: 'Review brand guidelines', applicableRole: 'Marketing Executive', department: 'Marketing', day: 'Day 1', priority: 'Medium', assignedBy: 'Marketing Manager', resourceId: 'R028', isMandatory: true, duration: '30 mins', desc: 'Review corporate brand voice, messaging guidelines, and approved media assets.' },
  { taskId: 'T038', taskName: 'Review marketing strategy', applicableRole: 'Marketing Executive', department: 'Marketing', day: 'Day 2', priority: 'Medium', assignedBy: 'Marketing Manager', resourceId: 'R029', isMandatory: true, duration: '45 mins', desc: 'Read quarterly GTM roadmap, target persona profiles, and campaign briefs.' },
  { taskId: 'T039', taskName: 'Get access to marketing analytics', applicableRole: 'Marketing Executive', department: 'Marketing', day: 'Day 2', priority: 'High', assignedBy: 'IT', resourceId: 'R030', isMandatory: true, duration: '20 mins', desc: 'Obtain permissions for campaign dashboards, conversion tracking, and CRM reports.' },
  { taskId: 'T040', taskName: 'Meet marketing team', applicableRole: 'Marketing Executive', department: 'Marketing', day: 'Day 3', priority: 'Medium', assignedBy: 'Manager', resourceId: null, isMandatory: true, duration: '45 mins', desc: 'Meet content strategists, performance marketers, and growth lead.' }
];

console.log('Script loaded. Total tasks:', ALL_40_TASKS.length);
